version: 2
jobs:
  lint:
    machine: true
    steps:
      - run: docker build -t circleci-poc-lint --file=./devops/lint/Dockerfile ./devops/lint
      - run: docker run circleci-poc-lint
      - run: echo "lint step"
  unit-test:
    machine: true
    steps:
      - run: docker build -t circleci-poc-unit-test --file=./devops/unit-test/Dockerfile ./devops/unit-test
      - run: docker run circleci-poc-unit-test
      - run: echo "unit test step"
  build:
    machine: true
    steps:
      - run: docker build -t circleci-poc-build --file=./devops/build/Dockerfile ./devops/build
      - run: docker run circleci-poc-build
      - run: echo "build step"
workflow:
  version: 2
  ci-flow:
    jobs:
      - lint
      - unit-test
      - build

