version: 2

defaults: &defaults
  working_directory: ~/app

jobs:
  lint:
    <<: *defaults
    machine: true
    steps:
      - run: docker build -t circleci-poc-lint --file=~/app/devops/lint/Dockerfile ~/app/devops/lint
      - run: docker run circleci-poc-lint
      - run: echo "lint step"
  unit-test:
    <<: *defaults
    machine: true
    steps:
      - run: docker build -t circleci-poc-unit-test --file=~/app/devops/unit-test/Dockerfile ~/app/devops/unit-test
      - run: docker run circleci-poc-unit-test
      - run: echo "unit test step"
  build:
    <<: *defaults
    machine: true
    steps:
      - run: docker build -t circleci-poc-build --file=~/app/devops/build/Dockerfile ~/app/devops/build
      - run: docker run circleci-poc-build
      - run: echo "build step"
workflow:
  version: 2
  ci-flow:
    jobs:
      - lint
      - unit-test
      - build

