version: 2

defaults: &defaults
  working_directory: ~/app

jobs:
  lint:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - run: docker build -t circleci-poc-lint --file=./devops/lint/Dockerfile ~/app/devops/lint
      - run: docker run circleci-poc-lint
      - run: echo "lint step"
  unit-test:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - run: docker build -t circleci-poc-unit-test --file=./devops/unit-test/Dockerfile ~/app/devops/unit-test
      - run: docker run circleci-poc-unit-test
      - run: echo "unit test step"
  build:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - run: docker build -t circleci-poc-build --file=./devops/build/Dockerfile ~/app/devops/build
      - run: docker run circleci-poc-build
      - run: echo "build step"

workflows:
  version: 2
  ci-flow:
    jobs:
      - lint
      - unit-test:
          requires:
            - lint
      - build:
          requires:
            - unit-test
  test-build-flow:
    jobs:
      - unit-test
      - build:
          requires:
            - unit-test
